# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 772)
        Form.setStyleSheet("#frame{\n"
"    border-image: url(:/background/background/background1.jpeg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain; /* 尝试使用 contain 属性 */}\n"
"#frame_button{\n"
"    background-color: rgba(0, 173, 255,120); \n"
"    background-repeat: no-repeat;\n"
"    background-position:;\n"
"    background-size: contain; /* 尝试使用 contain 属性 */}\n"
"QLabel {\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    border: 2px solid #2980b9;\n"
"}\n"
"#label_frame{\n"
"    font-size: 30px; /* 字体大小 */\n"
"    padding: 5px; /* 内边距 */\n"
"    text-align: center;    /* 水平居中 */\n"
"    vertical-align: middle; /* 垂直居中 */\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #2980b9; /* 边框颜色和宽度 */\n"
"}\n"
"\n"
"\n"
"#label_path{\n"
"    font-size: 30px; /* 字体大小 */\n"
"    padding: 5px; /* 内边距 */\n"
"    padding-left:0px;\n"
"    text-align: center;    /* 水平居中 */\n"
"    vertical-align: middle; /* 垂直居中 */\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: none; /* 边框颜色和宽度 */\n"
"}\n"
"\n"
"\n"
"QComboBox {\n"
"    background-color: #3498db; /* 按钮背景色 */\n"
"    color: white; /* 按钮文字颜色 */\n"
"    border: 2px solid #2980b9; /* 边框颜色和宽度 */\n"
"    border-radius: 10px; /* 圆角效果 */\n"
"    font-size: 30px; /* 字体大小 */\n"
"    padding: 5px; /* 内边距 */\n"
"    text-align: center;    /* 水平居中 */\n"
"    vertical-align: middle; /* 垂直居中 */   \n"
"}\n"
"QComboBox:hover { \n"
"color: red;\n"
"font-size: 29px; /* 字体大小 */\n"
"}\n"
"QPushButton[flat=\"false\"]{\n"
"    background-color: #3498db; /* 按钮背景色 */\n"
"    color: white; /* 按钮文字颜色 */\n"
"    border: 2px solid #2980b9; /* 边框颜色和宽度 */\n"
"    border-radius: 10px; /* 圆角效果 */\n"
"    font-size: 30px; /* 字体大小 */\n"
"    padding: 5px; /* 内边距 */\n"
"    text-align: center;    /* 水平居中 */\n"
"    vertical-align: middle; /* 垂直居中 */           \n"
"}\n"
"QPushButton[flat=\"false\"]:hover {\n"
"    color: red; /* 鼠标悬停时的文字颜色 */\n"
"    font-size: 29px; /* 鼠标悬停时放大字体 */\n"
"}\n"
"#select_model_Button{\n"
"    background-color: #3498db; /* 按钮背景色 */\n"
"    color: white; /* 按钮文字颜色 */\n"
"    border: 2px solid #2980b9; /* 边框颜色和宽度 */\n"
"    border-radius: 10px; /* 圆角效果 */\n"
"    font-size: 27px; /* 字体大小 */\n"
"    padding: 5px; /* 内边距 */\n"
"    text-align: center;    /* 水平居中 */\n"
"    vertical-align: middle; /* 垂直居中 */  \n"
"}\n"
"#select_model_Button:hover{\n"
"    color: red; /* 鼠标悬停时的文字颜色 */\n"
"    font-size: 26px; /* 鼠标悬停时放大字体 */\n"
"}\n"
"\n"
"\n"
"QPushButton:hover { \n"
"color: red;\n"
"font-size: 29px; /* 字体大小 */\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(255, 255, 255); /* 按钮背景色 */\n"
"    color:rgb(0, 0, 0); /* 按钮文字颜色 */\n"
"    border: 2px solid rgb(0, 0, 0); /* 边框颜色和宽度 */\n"
"    border-radius: 0px; /* 圆角效果 */\n"
"    font-size: 30px; /* 字体大小 */\n"
"    padding: 5px; /* 内边距 */\n"
"    text-align: left; /* 文字左对齐 */\n"
"    padding-left: 10px; /* 可选：设置文字左侧的间距 */\n"
"   \n"
"}\n"
"\n"
"QLabel[labelhead=false]{\n"
"    background: transparent; /* 背景透明 */\n"
"    border: none; /* 可选：移除边框 */         \n"
"    color: rgb(255, 255, 255) ;  \n"
"    font-size: 40px; /* 字体大小 */       /* 字体颜色 */\n"
"}\n"
"#label_title{\n"
"    background: transparent; /* 背景透明 */\n"
"    border: none; /* 可选：移除边框 */         \n"
"    color: rgb(255, 255, 255) ; \n"
"   font-size: 30px; /* 字体大小 */ \n"
"    \n"
"}\n"
"\n"
"#spinBox{\n"
"    font-size: 30px; /* 字体大小 */\n"
"    text-align: center; /* 文字左对齐 */\n"
"}\n"
"\n"
"\n"
"QRadioButton::unchecked{color:rgb(255, 0, 0);}\n"
"QRadioButton::checked{color:rgb(0, 255, 0);}\n"
"QRadioButton::indicator:checked {\n"
"    border-radius: 10px; /* 圆角效果 */\n"
"    background-color:rgb(0,255,0);\n"
"}\n"
"\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_title = QtWidgets.QLabel(self.frame_5)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.original_image = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_image.sizePolicy().hasHeightForWidth())
        self.original_image.setSizePolicy(sizePolicy)
        self.original_image.setMinimumSize(QtCore.QSize(0, 0))
        self.original_image.setText("")
        self.original_image.setProperty("show", False)
        self.original_image.setObjectName("original_image")
        self.horizontalLayout_5.addWidget(self.original_image)
        self.compare_image = QtWidgets.QLabel(self.frame_3)
        self.compare_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compare_image.sizePolicy().hasHeightForWidth())
        self.compare_image.setSizePolicy(sizePolicy)
        self.compare_image.setMinimumSize(QtCore.QSize(0, 0))
        self.compare_image.setText("")
        self.compare_image.setProperty("show", False)
        self.compare_image.setObjectName("compare_image")
        self.horizontalLayout_5.addWidget(self.compare_image)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.res_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.res_label.sizePolicy().hasHeightForWidth())
        self.res_label.setSizePolicy(sizePolicy)
        self.res_label.setText("")
        self.res_label.setObjectName("res_label")
        self.horizontalLayout_4.addWidget(self.res_label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_path = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        self.label_path.setMinimumSize(QtCore.QSize(0, 0))
        self.label_path.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_path.setObjectName("label_path")
        self.verticalLayout.addWidget(self.label_path)
        self.open_image_Button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_image_Button.sizePolicy().hasHeightForWidth())
        self.open_image_Button.setSizePolicy(sizePolicy)
        self.open_image_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.open_image_Button.setFlat(True)
        self.open_image_Button.setObjectName("open_image_Button")
        self.verticalLayout.addWidget(self.open_image_Button)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.detect_Button = QtWidgets.QPushButton(self.frame_6)
        self.detect_Button.setObjectName("detect_Button")
        self.horizontalLayout_3.addWidget(self.detect_Button)
        self.save_Button = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_Button.sizePolicy().hasHeightForWidth())
        self.save_Button.setSizePolicy(sizePolicy)
        self.save_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.save_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_Button.setObjectName("save_Button")
        self.horizontalLayout_3.addWidget(self.save_Button)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 7)
        self.verticalLayout_2.setStretch(2, 4)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "IJP检测"))
        self.label_path.setText(_translate("Form", "文件路径:"))
        self.open_image_Button.setText(_translate("Form", "选择图片"))
        self.detect_Button.setText(_translate("Form", "狭缝识别"))
        self.save_Button.setText(_translate("Form", "保存结果"))
import b1
